// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MoE.ECE.Domain.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ReferenceDataContext))]
    partial class ReferenceDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.EceLicencingDetailDateRangedParameter", b =>
                {
                    b.Property<int>("LicencingDetailHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("licencing_detail_history_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApplicationStatusDescription")
                        .HasColumnName("application_status_description")
                        .HasColumnType("text");

                    b.Property<int>("ApplicationStatusId")
                        .HasColumnName("application_status_id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveFromDate")
                        .HasColumnName("effective_from_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveToDate")
                        .HasColumnName("effective_to_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenceClassDescription")
                        .HasColumnName("licence_class_description")
                        .HasColumnType("text");

                    b.Property<int?>("LicenceClassId")
                        .HasColumnName("licence_class_id")
                        .HasColumnType("integer");

                    b.Property<string>("LicenceStatusDescription")
                        .HasColumnName("licence_status_description")
                        .HasColumnType("text");

                    b.Property<int>("LicenceStatusId")
                        .HasColumnName("licence_status_id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnName("modified_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RefOrganisationId")
                        .HasColumnName("ref_organisation_id")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceProvisionTypeDescription")
                        .HasColumnName("service_provision_type_description")
                        .HasColumnType("text");

                    b.Property<int?>("ServiceProvisionTypeId")
                        .HasColumnName("service_provision_type_id")
                        .HasColumnType("integer");

                    b.HasKey("LicencingDetailHistoryId")
                        .HasName("pk_ece_licencing_detail_date_ranged_parameters");

                    b.HasIndex("RefOrganisationId")
                        .HasName("ix_ece_licencing_detail_date_ranged_parameters_ref_organisatio");

                    b.ToTable("ece_licencing_detail_date_ranged_parameter", "referencedata");
                });

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.EceOperatingSession", b =>
                {
                    b.Property<int>("OperatingSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("operating_session_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnName("end_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FundedHours")
                        .HasColumnName("funded_hours")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxChildren")
                        .HasColumnName("max_children")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxChildrenUnder2")
                        .HasColumnName("max_children_under2")
                        .HasColumnType("integer");

                    b.Property<int>("OperatingHours")
                        .HasColumnName("operating_hours")
                        .HasColumnType("integer");

                    b.Property<int>("RefOrganisationId")
                        .HasColumnName("ref_organisation_id")
                        .HasColumnType("integer");

                    b.Property<string>("SessionDayDescription")
                        .HasColumnName("session_day_description")
                        .HasColumnType("text");

                    b.Property<int?>("SessionDayId")
                        .HasColumnName("session_day_id")
                        .HasColumnType("integer");

                    b.Property<string>("SessionProvisionTypeDescription")
                        .HasColumnName("session_provision_type_description")
                        .HasColumnType("text");

                    b.Property<int?>("SessionProvisionTypeId")
                        .HasColumnName("session_provision_type_id")
                        .HasColumnType("integer");

                    b.Property<string>("SessionTypeDescription")
                        .HasColumnName("session_type_description")
                        .HasColumnType("text");

                    b.Property<int?>("SessionTypeId")
                        .HasColumnName("session_type_id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnName("start_time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperatingSessionId")
                        .HasName("pk_ece_operating_sessions");

                    b.HasIndex("RefOrganisationId")
                        .HasName("ix_ece_operating_session_ref_organisation_id");

                    b.ToTable("ece_operating_session", "referencedata");
                });

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.EceOperatingSessionDateRangedParameter", b =>
                {
                    b.Property<int>("LicencingDetailHistoryId")
                        .HasColumnName("licencing_detail_history_id")
                        .HasColumnType("integer");

                    b.Property<int>("OperatingSessionId")
                        .HasColumnName("operating_session_id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveFromDate")
                        .HasColumnName("effective_from_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveToDate")
                        .HasColumnName("effective_to_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnName("end_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxChildren")
                        .HasColumnName("max_children")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxChildrenUnder2")
                        .HasColumnName("max_children_under2")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnName("modified_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RefOrganisationId")
                        .HasColumnName("ref_organisation_id")
                        .HasColumnType("integer");

                    b.Property<string>("SessionDayDescription")
                        .HasColumnName("session_day_description")
                        .HasColumnType("text");

                    b.Property<int?>("SessionDayId")
                        .HasColumnName("session_day_id")
                        .HasColumnType("integer");

                    b.Property<string>("SessionProvisionTypeDescription")
                        .HasColumnName("session_provision_type_description")
                        .HasColumnType("text");

                    b.Property<int?>("SessionProvisionTypeId")
                        .HasColumnName("session_provision_type_id")
                        .HasColumnType("integer");

                    b.Property<string>("SessionTypeDescription")
                        .HasColumnName("session_type_description")
                        .HasColumnType("text");

                    b.Property<int?>("SessionTypeId")
                        .HasColumnName("session_type_id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnName("start_time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LicencingDetailHistoryId", "OperatingSessionId")
                        .HasName("pk_ece_operating_session_date_ranged_parameters");

                    b.HasIndex("RefOrganisationId")
                        .HasName("ix_ece_operating_session_date_ranged_parameters_ref_organisati");

                    b.ToTable("ece_operating_session_date_ranged_parameter", "referencedata");
                });

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.EceService", b =>
                {
                    b.Property<int>("RefOrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ref_organisation_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApplicationStatusDescription")
                        .HasColumnName("application_status_description")
                        .HasColumnType("text");

                    b.Property<int>("ApplicationStatusId")
                        .HasColumnName("application_status_id")
                        .HasColumnType("integer");

                    b.Property<string>("EcQualityLevelDescription")
                        .HasColumnName("ec_quality_level_description")
                        .HasColumnType("text");

                    b.Property<int?>("EcQualityLevelId")
                        .HasColumnName("ec_quality_level_id")
                        .HasColumnType("integer");

                    b.Property<int?>("EceServiceProviderId")
                        .HasColumnName("ece_service_provider_id")
                        .HasColumnType("integer");

                    b.Property<string>("EceServiceProviderName")
                        .HasColumnName("ece_service_provider_name")
                        .HasColumnType("text");

                    b.Property<string>("EceServiceProviderNumber")
                        .HasColumnName("ece_service_provider_number")
                        .HasColumnType("text");

                    b.Property<string>("EceServiceProviderOwnershipTypeDescription")
                        .HasColumnName("ece_service_provider_ownership_type_description")
                        .HasColumnType("text");

                    b.Property<int?>("EceServiceProviderOwnershipTypeId")
                        .HasColumnName("ece_service_provider_ownership_type_id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EceServiceStatusDate")
                        .HasColumnName("ece_service_status_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EceServiceStatusReasonDescription")
                        .HasColumnName("ece_service_status_reason_description")
                        .HasColumnType("text");

                    b.Property<int?>("EceServiceStatusReasonId")
                        .HasColumnName("ece_service_status_reason_id")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<string>("EquityIndexDescription")
                        .HasColumnName("equity_index_description")
                        .HasColumnType("text");

                    b.Property<int?>("EquityIndexId")
                        .HasColumnName("equity_index_id")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalProviderId")
                        .HasColumnName("external_provider_id")
                        .HasColumnType("text");

                    b.Property<string>("FaxNumber")
                        .HasColumnName("fax_number")
                        .HasColumnType("text");

                    b.Property<bool?>("InstallmentPayments")
                        .HasColumnName("installment_payments")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFunded")
                        .HasColumnName("is_funded")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("IsolationIndex")
                        .HasColumnName("isolation_index")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("LicenceClassDescription")
                        .HasColumnName("licence_class_description")
                        .HasColumnType("text");

                    b.Property<int?>("LicenceClassId")
                        .HasColumnName("licence_class_id")
                        .HasColumnType("integer");

                    b.Property<string>("LicenceStatusDescription")
                        .HasColumnName("licence_status_description")
                        .HasColumnType("text");

                    b.Property<int>("LicenceStatusId")
                        .HasColumnName("licence_status_id")
                        .HasColumnType("integer");

                    b.Property<string>("LocationAddressLine1")
                        .HasColumnName("location_address_line1")
                        .HasColumnType("text");

                    b.Property<string>("LocationAddressLine2")
                        .HasColumnName("location_address_line2")
                        .HasColumnType("text");

                    b.Property<string>("LocationAddressLine3")
                        .HasColumnName("location_address_line3")
                        .HasColumnType("text");

                    b.Property<string>("LocationAddressLine4")
                        .HasColumnName("location_address_line4")
                        .HasColumnType("text");

                    b.Property<long?>("Nzbn")
                        .HasColumnName("nzbn")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("OpenDate")
                        .HasColumnName("open_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnName("organisation_name")
                        .HasColumnType("text");

                    b.Property<string>("OrganisationNumber")
                        .IsRequired()
                        .HasColumnName("organisation_number")
                        .HasColumnType("text");

                    b.Property<string>("OrganisationSectorRoleDescription")
                        .HasColumnName("organisation_sector_role_description")
                        .HasColumnType("text");

                    b.Property<int?>("OrganisationSectorRoleId")
                        .HasColumnName("organisation_sector_role_id")
                        .HasColumnType("integer");

                    b.Property<string>("OrganisationStatusDescription")
                        .HasColumnName("organisation_status_description")
                        .HasColumnType("text");

                    b.Property<int>("OrganisationStatusId")
                        .HasColumnName("organisation_status_id")
                        .HasColumnType("integer");

                    b.Property<string>("OrganisationTypeDescription")
                        .HasColumnName("organisation_type_description")
                        .HasColumnType("text");

                    b.Property<int>("OrganisationTypeId")
                        .HasColumnName("organisation_type_id")
                        .HasColumnType("integer");

                    b.Property<string>("OtherEmail")
                        .HasColumnName("other_email")
                        .HasColumnType("text");

                    b.Property<bool?>("ParentLedEligibleToOfferFree")
                        .HasColumnName("parent_led_eligible_to_offer_free")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phone_number")
                        .HasColumnType("text");

                    b.Property<string>("PostalAddressLine1")
                        .HasColumnName("postal_address_line1")
                        .HasColumnType("text");

                    b.Property<string>("PostalAddressLine2")
                        .HasColumnName("postal_address_line2")
                        .HasColumnType("text");

                    b.Property<string>("PostalAddressLine3")
                        .HasColumnName("postal_address_line3")
                        .HasColumnType("text");

                    b.Property<string>("PostalAddressLine4")
                        .HasColumnName("postal_address_line4")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryLanguageDescription")
                        .HasColumnName("primary_language_description")
                        .HasColumnType("text");

                    b.Property<int?>("PrimaryLanguageId")
                        .HasColumnName("primary_language_id")
                        .HasColumnType("integer");

                    b.Property<string>("RegionDescription")
                        .HasColumnName("region_description")
                        .HasColumnType("text");

                    b.Property<int?>("RegionId")
                        .HasColumnName("region_id")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceProvisionTypeDescription")
                        .HasColumnName("service_provision_type_description")
                        .HasColumnType("text");

                    b.Property<int?>("ServiceProvisionTypeId")
                        .HasColumnName("service_provision_type_id")
                        .HasColumnType("integer");

                    b.Property<bool?>("TeacherLedEligibleToOfferFree")
                        .HasColumnName("teacher_led_eligible_to_offer_free")
                        .HasColumnType("boolean");

                    b.Property<string>("Website")
                        .HasColumnName("website")
                        .HasColumnType("text");

                    b.HasKey("RefOrganisationId")
                        .HasName("pk_ece_services");

                    b.ToTable("ece_service", "referencedata");
                });

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.EceServiceDateRangedParameter", b =>
                {
                    b.Property<int>("HistoryId")
                        .HasColumnName("history_id")
                        .HasColumnType("integer");

                    b.Property<string>("AttributeSource")
                        .HasColumnName("attribute_source")
                        .HasColumnType("text");

                    b.Property<string>("Attribute")
                        .HasColumnName("attribute")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveFromDate")
                        .HasColumnName("effective_from_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveToDate")
                        .HasColumnName("effective_to_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArray")
                        .HasColumnName("is_array")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnName("modified_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RefOrganisationId")
                        .HasColumnName("ref_organisation_id")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnName("value")
                        .HasColumnType("text");

                    b.Property<string>("ValueDescription")
                        .HasColumnName("value_description")
                        .HasColumnType("text");

                    b.HasKey("HistoryId", "AttributeSource")
                        .HasName("pk_ece_service_date_ranged_parameters");

                    b.HasIndex("RefOrganisationId")
                        .HasName("ix_ece_service_date_ranged_parameters_ref_organisation_id");

                    b.ToTable("ece_service_date_ranged_parameter", "referencedata");
                });

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("EdumisCode")
                        .HasColumnName("edumis_code")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EffectiveFromDate")
                        .HasColumnName("effective_from_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveToDate")
                        .HasColumnName("effective_to_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LookupTypeId")
                        .HasColumnName("lookup_type_id")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentLookupId")
                        .HasColumnName("parent_lookup_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_lookups");

                    b.HasIndex("LookupTypeId")
                        .HasName("ix_lookups_lookup_type_id");

                    b.ToTable("lookup", "referencedata");
                });

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.LookupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_lookup_types");

                    b.ToTable("lookup_type", "referencedata");
                });

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.EceOperatingSession", b =>
                {
                    b.HasOne("MoE.ECE.Domain.Model.ReferenceData.EceService", "EceService")
                        .WithMany("OperatingSessions")
                        .HasForeignKey("RefOrganisationId")
                        .HasConstraintName("fk_ece_operating_session_ece_services_ece_service_ref_organisa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.EceOperatingSessionDateRangedParameter", b =>
                {
                    b.HasOne("MoE.ECE.Domain.Model.ReferenceData.EceLicencingDetailDateRangedParameter", "EceLicencingDetailDateRangedParameter")
                        .WithMany("EceOperatingSessionDateRangedParameters")
                        .HasForeignKey("LicencingDetailHistoryId")
                        .HasConstraintName("fk_ece_operating_session_date_ranged_parameters_ece_licencing_")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoE.ECE.Domain.Model.ReferenceData.Lookup", b =>
                {
                    b.HasOne("MoE.ECE.Domain.Model.ReferenceData.LookupType", null)
                        .WithMany("Lookups")
                        .HasForeignKey("LookupTypeId")
                        .HasConstraintName("fk_lookups_lookup_types_lookup_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
