name: '$(versionMajor).$(versionMinor).$(versionPatch)$(Rev:.r)'

trigger:
- master

schedules:
  - cron: "0 16 * * *" # Schedule earlier than first/integration pipelines 
    displayName: Morning build
    branches:
      include:
      - master
    always: 'true'

pool:
  vmImage: 'ubuntu-latest'

variables:
  versionMajor: 1
  versionMinor: 0
  versionPatch: 0
  decomDate: ''

  containerRegistry: 'mapaerscontainerregistry'
  prodUatAzureRMServiceConnection: 'DevOps-MOEEDUNZ-ERS-EDU-MOE-ERS-PRODUAT-01-FS'
  testDevAzureRMServiceConnection: 'DevOps-MOEEDUNZ-ERS-EDU-MOE-ERS-TESTDEV-01-FS'

resources:
  repositories:
    - repository: 'utilities' # repo for terraform, ado and other scripts and tools
      type: 'git'
      name: 'utilities'

    - repository: 'ERS-Environment-Release'
      type: 'git'
      name: 'ERS-Environment-Release'

extends:
  template: devops/approval-check.yml@ERS-Environment-Release
  parameters:
    releaseStages:
    - template: quality-gate.yml
      parameters:
        azureDevOpsServiceConnection: '$(testDevAzureRMServiceConnection)'
        azureKeyvaultInstance: 'mataersdev02secrets'

    - template: build-stage.yml    
      parameters:      
        azureDevOpsServiceConnection: '$(testDevAzureRMServiceConnection)'
        azureKeyvaultInstance: 'mataersdev02secrets'

    - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
      - template: release-stage.yml
        parameters:
          environmentPrefix: 'mata'
          environmentSuffix: 'devtest'
          environmentName: 'dev'
          environmentNumber: '00'
          azureDevOpsServiceConnection: '$(testDevAzureRMServiceConnection)'
          azureKeyvaultInstance: 'mataersdev00secrets'
          containerRegistry: '$(containerRegistry)'
          decomDate: '$(decomDate)'

    - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
      - template: release-stage.yml
        parameters:
            environmentPrefix: 'mata'
            environmentSuffix: 'devtest'
            environmentName: 'dev'
            environmentNumber: '02'
            azureDevOpsServiceConnection: '$(testDevAzureRMServiceConnection)'
            azureKeyvaultInstance: 'mataersdev02secrets'
            containerRegistry: '$(containerRegistry)'
            decomDate: '$(decomDate)'

      - template: release-stage.yml
        parameters:
            environmentPrefix: 'mata'
            environmentSuffix: 'devtest'
            environmentName: 'tst'
            environmentNumber: '02'
            azureDevOpsServiceConnection: '$(testDevAzureRMServiceConnection)'
            azureKeyvaultInstance: 'mataerstst02secrets'
            containerRegistry: '$(containerRegistry)'
            decomDate: '$(decomDate)'
