parameters:
  azureDevOpsServiceConnection: ''
  azureKeyvaultInstance: ''
stages:
  - stage: QualityGate
    variables:
      whiteSourceProjectName: 'ece-api'
    condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Schedule'))
    dependsOn: []
    jobs:
      - job: Quality_Checks
        steps:
        # Fix for 401 timeout issue against nuget feed (Support case #120110523002341)
        - bash: |
            echo "##vso[task.setvariable variable=NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS]120"
            echo "##vso[task.setvariable variable=NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS]120"
          displayName: "Set NuGet Auth Timeout Values" 

        # Auth to Azure Artifcats where the NuGet feed lives
        - task: NuGetAuthenticate@0
          displayName: 'NuGet Authenticate'
        
        - script: 
            docker pull postgres:latest
          displayName: 'Cache Docker Images for Tests'
        
        - task: SonarQubePrepare@4
          continueOnError: true
          displayName: 'Prepare analysis on SonarQube'
          inputs:
            SonarQube: 'SonarQube-ERS'
            projectKey: ERS-ece-api
            projectName: ERS-ece-api
            extraProperties: 'sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/**/coverage.opencover.xml' 
            
        - task: DotNetCoreCLI@2
          continueOnError: true
          displayName: 'Build for Quality checks'
          inputs:
            command: build
            projects: '**/ECE.sln'
            arguments: '-o $(Build.ArtifactStagingDirectory)'
            
        - task: AzureKeyVault@1
          condition: succeeded()
          displayName: 'Get OPA Secret from Key Vault'
          inputs:
            azureSubscription: '${{ parameters.azureDevOpsServiceConnection }}'
            keyVaultName: '${{ parameters.azureKeyvaultInstance }}'
            secretsFilter: 'OPASettings--UserSecret' # Options: editableOptions
          continueOnError: false

        - task: geeklearningio.gl-vsts-tasks-file-patch.json-patch-task.JsonPatch@3
          condition: succeeded()
          displayName: 'Set OPA Settings For Integration Tests'
          inputs:
            JsonWorkingDir: '$(Build.SourcesDirectory)/Test/Integration'
            JsonTargetFilters: appsettings.integration-test.json
            JsonPatchContent: |
              = /OpaSettings/UserName => "ersuser"
              = /OpaSettings/UserSecret => "$(OPASettings--UserSecret)"               
            OutputPatchFile: true
            ProduceJson5: true
            FailIfNoPatchApplied: true
          continueOnError: false

        - task: DotNetCoreCLI@2
          displayName: Run All Unit Tests (Integ. Tests disabled for now)
          inputs:
            command: test
            arguments: '--collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover'
            projects: '**/Unit.Tests.csproj'   
        
        - task: SonarQubeAnalyze@4
          continueOnError: true
          displayName: 'Run Code Analysis'

        - task: SonarQubePublish@4
          continueOnError: true
          displayName: 'Publish Quality Gate Result'
        
        - task: AzureKeyVault@1
          condition: succeeded()
          displayName: 'Get Whitesource API Key from Key Vault'
          inputs:
            azureSubscription: '${{ parameters.azureDevOpsServiceConnection }}'
            keyVaultName: 'mataersdevtestsecrets'
            secretsFilter: 'whitesource-api-key' # Options: editableOptions
          continueOnError: false

        - script: 'curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar'
          displayName: 'Download Whitesource Agent'

        - script: 'java -jar wss-unified-agent.jar -c ./devops/whitesource-default-csharp.config -apiKey "$(whitesource-api-key)" -product ERS -project $(whiteSourceProjectName) -d .'
          displayName: 'Whitesource Code Scan'
          continueOnError: true 
 
        - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
          - script: 'java -jar wss-unified-agent.jar -c ./devops/whitesource-eua-csharp.config -apiKey "$(whitesource-api-key)" -product ERS -project $(whiteSourceProjectName) -appPath $(Build.ArtifactStagingDirectory)/Web.dll -d .'
            displayName: 'Whitesource EUA Scan Entrypoint'
            continueOnError: true

          - script: 'java -jar wss-unified-agent.jar -c ./devops/whitesource-eua-csharp.config -apiKey "$(whitesource-api-key)" -product ERS -project $(whiteSourceProjectName) -appPath $(Build.ArtifactStagingDirectory)/CLI.dll -d .'
            displayName: 'Whitesource EUA Scan CLI'
            continueOnError: true 