parameters:
  environmentPrefix: ''
  environmentSuffix: ''
  environmentName: ''
  environmentNumber: ''
  applicationName: ''
  releaseStageDescriptor: ''
  azureDevOpsServiceConnection: ''
  runTerraformDestroy: false
  runTerraformApply: true
  terraformVersion: 'latest'
  decomDate: ''
       
steps:
- pwsh: |
    $stateResourceGroup = "${{ parameters.environmentPrefix }}-ERS-${{ parameters.environmentSuffix }}-TFSTATE".ToUpper()
    $stateStorageAccount = ($stateResourceGroup -replace "\W","").ToLower()
    $stateContainer = "tfstate-${{ parameters.environmentName }}-${{ parameters.environmentNumber }}".ToLower()

    $actiongroup_resource_group = "${{ parameters.environmentPrefix }}-ERS-${{ parameters.environmentSuffix }}-MASTER".ToUpper()
    $actiongroup_name = "${{ parameters.environmentSuffix }}".ToUpper() + "-ActionGroup"
    
    Write-Output "##vso[task.setvariable variable=actiongroup_resource_group]$actiongroup_resource_group"
    Write-Output "Set variable [actiongroup_resource_group] to [$actiongroup_resource_group]"

    Write-Output "##vso[task.setvariable variable=actiongroup_name]$actiongroup_name"
    Write-Output "Set variable [actiongroup_name] to [$actiongroup_name]"
      
    Write-Output "##vso[task.setvariable variable=stateResourceGroup]$stateResourceGroup"
    Write-Output "Set variable [stateResourceGroup] to [$stateResourceGroup]"

    Write-Output "##vso[task.setvariable variable=stateStorageAccount]$stateStorageAccount"
    Write-Output "Set variable [stateStorageAccount] to [$stateStorageAccount]"

    Write-Output "##vso[task.setvariable variable=stateContainer]$stateContainer"
    Write-Output "Set variable [stateContainer] to [$stateContainer]"
  continueOnError: false
  displayName: 'Initialise Variables'

- template: terraform/terraform-lint.yml@utilities

- ${{ if eq(parameters.runTerraformDestroy, true) }}:
  # Teardown any active sessions to the database before terraform destroy
  # Create a connection string, revoke access, and terminate any sessions to the database
  - task: AzureCLI@2
    displayName: 'Terraform App: Prep PSQL DB for deletion'
    inputs:
      azureSubscription: "${{ parameters.azureDevOpsServiceConnection }}"
      scriptType: pscore
      scriptLocation: inlineScript
      failOnStandardError: false
      powerShellErrorActionPreference: 'silentlyContinue'
      inlineScript: |
        $keyvaultName = "${{ parameters.environmentPrefix }}ers${{ parameters.environmentSuffix }}secrets"
        $secretName = "psqlserveradmin-password" 
        $env:PGPASSWORD = az keyvault secret show --vault-name "$keyvaultName" --name "$secretName" -o tsv --query value
        if ([string]::IsNullOrEmpty($env:PGPASSWORD)) {
          echo "##vso[task.logissue type=warning] Failed to get database credentials. This is not normal."
          exit 0
        }
        # Use psql client (or CLI?) to revoke and terminate existing DB connections otherwise destroy fails with active sessions
        echo "Installing postgresql-client.."
        sudo apt install -y postgresql-client
        psql -V

        $dbServerName = "${{ parameters.environmentPrefix }}ers${{ parameters.environmentSuffix }}psqlserver".ToLower()
        $dbName = "${{ parameters.environmentPrefix }}ers${{ parameters.environmentName }}${{ parameters.environmentnumber }}psql${{ parameters.applicationName }}".ToLower()
        $dbEndpoint = "$dbServerName.postgres.database.azure.com"
        $dbUsername = "psqlserveradmin"

        $dbConnectionString = "host=$dbEndpoint port=5432 user='$dbUsername@$dbServerName' dbname=postgres sslmode=require"
        $revokeAccessSqlCommand = @"
        alter database $dbName allow_connections = off;
        REVOKE CONNECT ON DATABASE $dbName FROM PUBLIC;
        SELECT pg_terminate_backend(pid) 
        FROM pg_stat_activity 
        WHERE pid <> pg_backend_pid() AND datname = '$dbName';
        "@

        Write-Output "Command: $revokeAccessSqlCommand"
        Write-Output "ConnString: $dbConnectionString"

        echo "Revoking access and terminating sessions to db $dbName .."
        psql -d "$dbConnectionString" -c "$revokeAccessSqlCommand"
        if ($LASTEXITCODE -ne 0) {
          Write-Output "Failed to revoke DB access. Try to continue gracefully.."
          exit 0
        }
    continueOnError: true

  - task: AzureCLI@2
    condition: succeeded()
    displayName: 'Terraform destroy ECE App'
    inputs:
      azureSubscription: "${{ parameters.azureDevOpsServiceConnection }}"
      scriptType: pscore
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      workingDirectory: "$(Build.SourcesDirectory)/devops/terraform"
      inlineScript: |
        $backendConfig = @"
        terraform {
          backend "azurerm" {
            resource_group_name  = "$(stateResourceGroup)"
            storage_account_name = "$(stateStorageAccount)"
            container_name       = "$(stateContainer)"
            key                  = "${{ parameters.applicationname }}"
          }
        }
        "@

        # Override the backend.tf in the repository before applying to a real environment
        $backendConfig | Out-File "backend_override.tf" -Encoding utf8 -Force
        cat "backend_override.tf"

        $subscriptionId = (az account show --query id).Replace("`"","")
        $dockerCommandBase = "docker run -e ARM_CLIENT_ID=$env:servicePrincipalId -e ARM_CLIENT_SECRET=$env:servicePrincipalKey -e ARM_SUBSCRIPTION_ID=$subscriptionId -e ARM_TENANT_ID=$env:tenantId -v $(PWD):/workspace -w /workspace hashicorp/terraform:${{ parameters.terraformVersion }}"
        Invoke-Expression ("$dockerCommandBase init")
        Invoke-Expression ("$dockerCommandBase validate")

        $tfArgs = "-var='environment=${{ parameters.environmentName }}-${{ parameters.environmentNumber }}' -var='environment_prefix=${{ parameters.environmentPrefix }}' -var='environment_suffix=${{ parameters.environmentSuffix }}' -var='actiongroup_name=$(actiongroup_name)' -var='actiongroup_resource_group=$(actiongroup_resource_group)'"
        Invoke-Expression ("$dockerCommandBase destroy $tfArgs -auto-approve")
        if ($LASTEXITCODE -ne 0) {
          Write-Output "Error destroying resources."
          exit 1
        }
    continueOnError: false
    
- ${{ if eq(parameters.runTerraformApply, true) }}:
  - task: AzureCLI@2
    condition: succeeded()
    displayName: 'Generate Plan and Apply for ECE App'
    inputs:
      azureSubscription: "${{ parameters.azureDevOpsServiceConnection }}"
      scriptType: pscore
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      workingDirectory: "$(Build.SourcesDirectory)/devops/terraform"
      inlineScript: |
        $backendConfig = @"
        terraform {
          backend "azurerm" {
            resource_group_name  = "$(stateResourceGroup)"
            storage_account_name = "$(stateStorageAccount)"
            container_name       = "$(stateContainer)"
            key                  = "${{ parameters.applicationname }}"
          }
        }
        "@
                          
        # Override the backend.tf in the repository before applying to a real environment
        $backendConfig | Out-File "backend_override.tf" -Encoding utf8 -Force
        cat "backend_override.tf"

        $subscriptionId = (az account show --query id -o tsv)
        $dockerCommandBase = "docker run -e ARM_CLIENT_ID=$env:servicePrincipalId -e ARM_CLIENT_SECRET=$env:servicePrincipalKey -e ARM_SUBSCRIPTION_ID=$subscriptionId -e ARM_TENANT_ID=$env:tenantId -v $(PWD):/workspace -w /workspace hashicorp/terraform:${{ parameters.terraformVersion }}"
        Invoke-Expression ("$dockerCommandBase init")
        Invoke-Expression ("$dockerCommandBase validate")

        $terraformApplied = 'No'
        
        # The below will output the plan (if any changes/additions or removals) while having anything matching the regex pattern with "***"
        (Invoke-Expression ("$dockerCommandBase plan -detailed-exitcode -out=plan -var='environment=${{ parameters.environmentName }}-${{ parameters.environmentNumber }}' -var='environment_prefix=${{ parameters.environmentPrefix }}' -var='environment_suffix=${{ parameters.environmentSuffix }}' -var='actiongroup_name=$(actiongroup_name)' -var='actiongroup_resource_group=$(actiongroup_resource_group)' -var='decom_date=${{ parameters.decomDate }}'")) -replace "((.*)(docker|password|username|secret|key)([^=]+)= ).*", '$1"***"'
        if ($LASTEXITCODE -eq 0){
          Write-Output "No change to infrastructure, skipping 'Apply'."
        }elseif($LASTEXITCODE -eq 1){
          Write-Host "##vso[task.logissue type=error]Error occurred running terraform plan."
          exit 1
        }else{
          Write-Output "Plan has changes, running 'Apply'."
          Invoke-Expression ("$dockerCommandBase apply 'plan'")
          if($LASTEXITCODE -eq 1){
            Write-Host "##vso[task.logissue type=error]Error occurred running terraform apply."
            exit 1
          }
          $terraformApplied = 'Yes'
        }
    continueOnError: false
