// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ece/Submitted.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Events.Integration.Protobuf.Ece {

  /// <summary>Holder for reflection information generated from ece/Submitted.proto</summary>
  public static partial class SubmittedReflection {

    #region Descriptor
    /// <summary>File descriptor for ece/Submitted.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SubmittedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNlY2UvU3VibWl0dGVkLnByb3RvGhZwcm90b2J1Zi1uZXQvYmNsLnByb3Rv",
            "IogBCglTdWJtaXR0ZWQSIwoQQnVzaW5lc3NFbnRpdHlJZBgBIAEoCzIJLmJj",
            "bC5HdWlkEhYKDk9yZ2FuaXNhdGlvbklkGAIgASgFEg4KBlVuZGVyMhgDIAEo",
            "BRINCgVPdmVyMhgEIAEoBRIPCgdIb3VyczIwGAUgASgFEg4KBlBsdXMxMBgG",
            "IAEoBUIiqgIfRXZlbnRzLkludGVncmF0aW9uLlByb3RvYnVmLkVjZWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ProtoBuf.Bcl.BclReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Events.Integration.Protobuf.Ece.Submitted), global::Events.Integration.Protobuf.Ece.Submitted.Parser, new[]{ "BusinessEntityId", "OrganisationId", "Under2", "Over2", "Hours20", "Plus10" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///Notional Roll Submitted
  /// </summary>
  public sealed partial class Submitted : pb::IMessage<Submitted>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Submitted> _parser = new pb::MessageParser<Submitted>(() => new Submitted());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Submitted> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Events.Integration.Protobuf.Ece.SubmittedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Submitted() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Submitted(Submitted other) : this() {
      businessEntityId_ = other.businessEntityId_ != null ? other.businessEntityId_.Clone() : null;
      organisationId_ = other.organisationId_;
      under2_ = other.under2_;
      over2_ = other.over2_;
      hours20_ = other.hours20_;
      plus10_ = other.plus10_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Submitted Clone() {
      return new Submitted(this);
    }

    /// <summary>Field number for the "BusinessEntityId" field.</summary>
    public const int BusinessEntityIdFieldNumber = 1;
    private global::ProtoBuf.Bcl.Guid businessEntityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtoBuf.Bcl.Guid BusinessEntityId {
      get { return businessEntityId_; }
      set {
        businessEntityId_ = value;
      }
    }

    /// <summary>Field number for the "OrganisationId" field.</summary>
    public const int OrganisationIdFieldNumber = 2;
    private int organisationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int OrganisationId {
      get { return organisationId_; }
      set {
        organisationId_ = value;
      }
    }

    /// <summary>Field number for the "Under2" field.</summary>
    public const int Under2FieldNumber = 3;
    private int under2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Under2 {
      get { return under2_; }
      set {
        under2_ = value;
      }
    }

    /// <summary>Field number for the "Over2" field.</summary>
    public const int Over2FieldNumber = 4;
    private int over2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Over2 {
      get { return over2_; }
      set {
        over2_ = value;
      }
    }

    /// <summary>Field number for the "Hours20" field.</summary>
    public const int Hours20FieldNumber = 5;
    private int hours20_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hours20 {
      get { return hours20_; }
      set {
        hours20_ = value;
      }
    }

    /// <summary>Field number for the "Plus10" field.</summary>
    public const int Plus10FieldNumber = 6;
    private int plus10_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Plus10 {
      get { return plus10_; }
      set {
        plus10_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Submitted);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Submitted other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BusinessEntityId, other.BusinessEntityId)) return false;
      if (OrganisationId != other.OrganisationId) return false;
      if (Under2 != other.Under2) return false;
      if (Over2 != other.Over2) return false;
      if (Hours20 != other.Hours20) return false;
      if (Plus10 != other.Plus10) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (businessEntityId_ != null) hash ^= BusinessEntityId.GetHashCode();
      if (OrganisationId != 0) hash ^= OrganisationId.GetHashCode();
      if (Under2 != 0) hash ^= Under2.GetHashCode();
      if (Over2 != 0) hash ^= Over2.GetHashCode();
      if (Hours20 != 0) hash ^= Hours20.GetHashCode();
      if (Plus10 != 0) hash ^= Plus10.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (businessEntityId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BusinessEntityId);
      }
      if (OrganisationId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(OrganisationId);
      }
      if (Under2 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Under2);
      }
      if (Over2 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Over2);
      }
      if (Hours20 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Hours20);
      }
      if (Plus10 != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Plus10);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (businessEntityId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BusinessEntityId);
      }
      if (OrganisationId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(OrganisationId);
      }
      if (Under2 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Under2);
      }
      if (Over2 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Over2);
      }
      if (Hours20 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Hours20);
      }
      if (Plus10 != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Plus10);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (businessEntityId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BusinessEntityId);
      }
      if (OrganisationId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrganisationId);
      }
      if (Under2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Under2);
      }
      if (Over2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Over2);
      }
      if (Hours20 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hours20);
      }
      if (Plus10 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Plus10);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Submitted other) {
      if (other == null) {
        return;
      }
      if (other.businessEntityId_ != null) {
        if (businessEntityId_ == null) {
          BusinessEntityId = new global::ProtoBuf.Bcl.Guid();
        }
        BusinessEntityId.MergeFrom(other.BusinessEntityId);
      }
      if (other.OrganisationId != 0) {
        OrganisationId = other.OrganisationId;
      }
      if (other.Under2 != 0) {
        Under2 = other.Under2;
      }
      if (other.Over2 != 0) {
        Over2 = other.Over2;
      }
      if (other.Hours20 != 0) {
        Hours20 = other.Hours20;
      }
      if (other.Plus10 != 0) {
        Plus10 = other.Plus10;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (businessEntityId_ == null) {
              BusinessEntityId = new global::ProtoBuf.Bcl.Guid();
            }
            input.ReadMessage(BusinessEntityId);
            break;
          }
          case 16: {
            OrganisationId = input.ReadInt32();
            break;
          }
          case 24: {
            Under2 = input.ReadInt32();
            break;
          }
          case 32: {
            Over2 = input.ReadInt32();
            break;
          }
          case 40: {
            Hours20 = input.ReadInt32();
            break;
          }
          case 48: {
            Plus10 = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (businessEntityId_ == null) {
              BusinessEntityId = new global::ProtoBuf.Bcl.Guid();
            }
            input.ReadMessage(BusinessEntityId);
            break;
          }
          case 16: {
            OrganisationId = input.ReadInt32();
            break;
          }
          case 24: {
            Under2 = input.ReadInt32();
            break;
          }
          case 32: {
            Over2 = input.ReadInt32();
            break;
          }
          case 40: {
            Hours20 = input.ReadInt32();
            break;
          }
          case 48: {
            Plus10 = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
