// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ece_shared/FundingPeriodMonth.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Events.Integration.Protobuf.Shared {

  /// <summary>Holder for reflection information generated from ece_shared/FundingPeriodMonth.proto</summary>
  public static partial class FundingPeriodMonthReflection {

    #region Descriptor
    /// <summary>File descriptor for ece_shared/FundingPeriodMonth.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FundingPeriodMonthReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNlY2Vfc2hhcmVkL0Z1bmRpbmdQZXJpb2RNb250aC5wcm90bypIChJGdW5k",
            "aW5nUGVyaW9kTW9udGgSDwoLVU5TUEVDSUZJRUQQABIJCgVNYXJjaBADEggK",
            "BEp1bHkQBxIMCghOb3ZlbWJlchALQiWqAiJFdmVudHMuSW50ZWdyYXRpb24u",
            "UHJvdG9idWYuU2hhcmVkYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Events.Integration.Protobuf.Shared.FundingPeriodMonth), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum FundingPeriodMonth {
    [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("March")] March = 3,
    [pbr::OriginalName("July")] July = 7,
    [pbr::OriginalName("November")] November = 11,
  }

  #endregion

}

#endregion Designer generated code
