// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: eli/Rs7Received.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Events.Integration.Protobuf.Eli {

  /// <summary>Holder for reflection information generated from eli/Rs7Received.proto</summary>
  public static partial class Rs7ReceivedReflection {

    #region Descriptor
    /// <summary>File descriptor for eli/Rs7Received.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Rs7ReceivedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVlbGkvUnM3UmVjZWl2ZWQucHJvdG8aH3NoYXJlZC9GdW5kaW5nUGVyaW9k",
            "TW9udGgucHJvdG8i+QEKC1JzN1JlY2VpdmVkEhoKEk9yZ2FuaXNhdGlvbk51",
            "bWJlchgBIAEoCRIqCg1GdW5kaW5nUGVyaW9kGAIgASgOMhMuRnVuZGluZ1Bl",
            "cmlvZE1vbnRoEicKDUFkdmFuY2VNb250aHMYAyADKAsyEC5SczdBZHZhbmNl",
            "TW9udGgSLwoRRW50aXRsZW1lbnRNb250aHMYBCADKAsyFC5SczdFbnRpdGxl",
            "bWVudE1vbnRoEiQKC0RlY2xhcmF0aW9uGAUgASgLMg8uUnM3RGVjbGFyYXRp",
            "b24SEgoKSXNBdHRlc3RlZBgGIAEoCBIOCgZTb3VyY2UYByABKAkiagoPUnM3",
            "QWR2YW5jZU1vbnRoEhMKC01vbnRoTnVtYmVyGAIgASgFEgwKBFllYXIYAyAB",
            "KAUSDgoGQWxsRGF5GAQgASgFEhEKCVNlc3Npb25hbBgFIAEoBRIRCglQYXJl",
            "bnRMZWQYBiABKAUiZgoTUnM3RW50aXRsZW1lbnRNb250aBIKCgJJZBgBIAEo",
            "BRITCgtNb250aE51bWJlchgCIAEoBRIMCgRZZWFyGAMgASgFEiAKBERheXMY",
            "BCADKAsyEi5SczdFbnRpdGxlbWVudERheSJNCg5SczdEZWNsYXJhdGlvbhIQ",
            "CghGdWxsTmFtZRgCIAEoCRIUCgxDb250YWN0UGhvbmUYAyABKAkSEwoLRGVz",
            "aWduYXRpb24YBCABKAkimgEKEVJzN0VudGl0bGVtZW50RGF5EhEKCURheU51",
            "bWJlchgBIAEoBRIOCgZVbmRlcjIYAiABKAUSEgoKVHdvQW5kT3ZlchgDIAEo",
            "BRIPCgdIb3VyczIwGAQgASgFEg4KBlBsdXMxMBgFIAEoBRIUCgxDZXJ0aWZp",
            "Y2F0ZWQYBiABKAUSFwoPTm9uQ2VydGlmaWNhdGVkGAcgASgFQiKqAh9FdmVu",
            "dHMuSW50ZWdyYXRpb24uUHJvdG9idWYuRWxpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Events.Integration.Protobuf.Shared.FundingPeriodMonthReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Events.Integration.Protobuf.Eli.Rs7Received), global::Events.Integration.Protobuf.Eli.Rs7Received.Parser, new[]{ "OrganisationNumber", "FundingPeriod", "AdvanceMonths", "EntitlementMonths", "Declaration", "IsAttested", "Source" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Events.Integration.Protobuf.Eli.Rs7AdvanceMonth), global::Events.Integration.Protobuf.Eli.Rs7AdvanceMonth.Parser, new[]{ "MonthNumber", "Year", "AllDay", "Sessional", "ParentLed" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Events.Integration.Protobuf.Eli.Rs7EntitlementMonth), global::Events.Integration.Protobuf.Eli.Rs7EntitlementMonth.Parser, new[]{ "Id", "MonthNumber", "Year", "Days" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Events.Integration.Protobuf.Eli.Rs7Declaration), global::Events.Integration.Protobuf.Eli.Rs7Declaration.Parser, new[]{ "FullName", "ContactPhone", "Designation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Events.Integration.Protobuf.Eli.Rs7EntitlementDay), global::Events.Integration.Protobuf.Eli.Rs7EntitlementDay.Parser, new[]{ "DayNumber", "Under2", "TwoAndOver", "Hours20", "Plus10", "Certificated", "NonCertificated" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Rs7Received : pb::IMessage<Rs7Received>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Rs7Received> _parser = new pb::MessageParser<Rs7Received>(() => new Rs7Received());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Rs7Received> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Events.Integration.Protobuf.Eli.Rs7ReceivedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7Received() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7Received(Rs7Received other) : this() {
      organisationNumber_ = other.organisationNumber_;
      fundingPeriod_ = other.fundingPeriod_;
      advanceMonths_ = other.advanceMonths_.Clone();
      entitlementMonths_ = other.entitlementMonths_.Clone();
      declaration_ = other.declaration_ != null ? other.declaration_.Clone() : null;
      isAttested_ = other.isAttested_;
      source_ = other.source_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7Received Clone() {
      return new Rs7Received(this);
    }

    /// <summary>Field number for the "OrganisationNumber" field.</summary>
    public const int OrganisationNumberFieldNumber = 1;
    private string organisationNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrganisationNumber {
      get { return organisationNumber_; }
      set {
        organisationNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FundingPeriod" field.</summary>
    public const int FundingPeriodFieldNumber = 2;
    private global::Events.Integration.Protobuf.Shared.FundingPeriodMonth fundingPeriod_ = global::Events.Integration.Protobuf.Shared.FundingPeriodMonth.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Events.Integration.Protobuf.Shared.FundingPeriodMonth FundingPeriod {
      get { return fundingPeriod_; }
      set {
        fundingPeriod_ = value;
      }
    }

    /// <summary>Field number for the "AdvanceMonths" field.</summary>
    public const int AdvanceMonthsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Events.Integration.Protobuf.Eli.Rs7AdvanceMonth> _repeated_advanceMonths_codec
        = pb::FieldCodec.ForMessage(26, global::Events.Integration.Protobuf.Eli.Rs7AdvanceMonth.Parser);
    private readonly pbc::RepeatedField<global::Events.Integration.Protobuf.Eli.Rs7AdvanceMonth> advanceMonths_ = new pbc::RepeatedField<global::Events.Integration.Protobuf.Eli.Rs7AdvanceMonth>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Events.Integration.Protobuf.Eli.Rs7AdvanceMonth> AdvanceMonths {
      get { return advanceMonths_; }
    }

    /// <summary>Field number for the "EntitlementMonths" field.</summary>
    public const int EntitlementMonthsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Events.Integration.Protobuf.Eli.Rs7EntitlementMonth> _repeated_entitlementMonths_codec
        = pb::FieldCodec.ForMessage(34, global::Events.Integration.Protobuf.Eli.Rs7EntitlementMonth.Parser);
    private readonly pbc::RepeatedField<global::Events.Integration.Protobuf.Eli.Rs7EntitlementMonth> entitlementMonths_ = new pbc::RepeatedField<global::Events.Integration.Protobuf.Eli.Rs7EntitlementMonth>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Events.Integration.Protobuf.Eli.Rs7EntitlementMonth> EntitlementMonths {
      get { return entitlementMonths_; }
    }

    /// <summary>Field number for the "Declaration" field.</summary>
    public const int DeclarationFieldNumber = 5;
    private global::Events.Integration.Protobuf.Eli.Rs7Declaration declaration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Events.Integration.Protobuf.Eli.Rs7Declaration Declaration {
      get { return declaration_; }
      set {
        declaration_ = value;
      }
    }

    /// <summary>Field number for the "IsAttested" field.</summary>
    public const int IsAttestedFieldNumber = 6;
    private bool isAttested_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsAttested {
      get { return isAttested_; }
      set {
        isAttested_ = value;
      }
    }

    /// <summary>Field number for the "Source" field.</summary>
    public const int SourceFieldNumber = 7;
    private string source_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Source {
      get { return source_; }
      set {
        source_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Rs7Received);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Rs7Received other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrganisationNumber != other.OrganisationNumber) return false;
      if (FundingPeriod != other.FundingPeriod) return false;
      if(!advanceMonths_.Equals(other.advanceMonths_)) return false;
      if(!entitlementMonths_.Equals(other.entitlementMonths_)) return false;
      if (!object.Equals(Declaration, other.Declaration)) return false;
      if (IsAttested != other.IsAttested) return false;
      if (Source != other.Source) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OrganisationNumber.Length != 0) hash ^= OrganisationNumber.GetHashCode();
      if (FundingPeriod != global::Events.Integration.Protobuf.Shared.FundingPeriodMonth.Unspecified) hash ^= FundingPeriod.GetHashCode();
      hash ^= advanceMonths_.GetHashCode();
      hash ^= entitlementMonths_.GetHashCode();
      if (declaration_ != null) hash ^= Declaration.GetHashCode();
      if (IsAttested != false) hash ^= IsAttested.GetHashCode();
      if (Source.Length != 0) hash ^= Source.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrganisationNumber.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganisationNumber);
      }
      if (FundingPeriod != global::Events.Integration.Protobuf.Shared.FundingPeriodMonth.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) FundingPeriod);
      }
      advanceMonths_.WriteTo(output, _repeated_advanceMonths_codec);
      entitlementMonths_.WriteTo(output, _repeated_entitlementMonths_codec);
      if (declaration_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Declaration);
      }
      if (IsAttested != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsAttested);
      }
      if (Source.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Source);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrganisationNumber.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganisationNumber);
      }
      if (FundingPeriod != global::Events.Integration.Protobuf.Shared.FundingPeriodMonth.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) FundingPeriod);
      }
      advanceMonths_.WriteTo(ref output, _repeated_advanceMonths_codec);
      entitlementMonths_.WriteTo(ref output, _repeated_entitlementMonths_codec);
      if (declaration_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Declaration);
      }
      if (IsAttested != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsAttested);
      }
      if (Source.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Source);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OrganisationNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganisationNumber);
      }
      if (FundingPeriod != global::Events.Integration.Protobuf.Shared.FundingPeriodMonth.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FundingPeriod);
      }
      size += advanceMonths_.CalculateSize(_repeated_advanceMonths_codec);
      size += entitlementMonths_.CalculateSize(_repeated_entitlementMonths_codec);
      if (declaration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Declaration);
      }
      if (IsAttested != false) {
        size += 1 + 1;
      }
      if (Source.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Source);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Rs7Received other) {
      if (other == null) {
        return;
      }
      if (other.OrganisationNumber.Length != 0) {
        OrganisationNumber = other.OrganisationNumber;
      }
      if (other.FundingPeriod != global::Events.Integration.Protobuf.Shared.FundingPeriodMonth.Unspecified) {
        FundingPeriod = other.FundingPeriod;
      }
      advanceMonths_.Add(other.advanceMonths_);
      entitlementMonths_.Add(other.entitlementMonths_);
      if (other.declaration_ != null) {
        if (declaration_ == null) {
          Declaration = new global::Events.Integration.Protobuf.Eli.Rs7Declaration();
        }
        Declaration.MergeFrom(other.Declaration);
      }
      if (other.IsAttested != false) {
        IsAttested = other.IsAttested;
      }
      if (other.Source.Length != 0) {
        Source = other.Source;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrganisationNumber = input.ReadString();
            break;
          }
          case 16: {
            FundingPeriod = (global::Events.Integration.Protobuf.Shared.FundingPeriodMonth) input.ReadEnum();
            break;
          }
          case 26: {
            advanceMonths_.AddEntriesFrom(input, _repeated_advanceMonths_codec);
            break;
          }
          case 34: {
            entitlementMonths_.AddEntriesFrom(input, _repeated_entitlementMonths_codec);
            break;
          }
          case 42: {
            if (declaration_ == null) {
              Declaration = new global::Events.Integration.Protobuf.Eli.Rs7Declaration();
            }
            input.ReadMessage(Declaration);
            break;
          }
          case 48: {
            IsAttested = input.ReadBool();
            break;
          }
          case 58: {
            Source = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OrganisationNumber = input.ReadString();
            break;
          }
          case 16: {
            FundingPeriod = (global::Events.Integration.Protobuf.Shared.FundingPeriodMonth) input.ReadEnum();
            break;
          }
          case 26: {
            advanceMonths_.AddEntriesFrom(ref input, _repeated_advanceMonths_codec);
            break;
          }
          case 34: {
            entitlementMonths_.AddEntriesFrom(ref input, _repeated_entitlementMonths_codec);
            break;
          }
          case 42: {
            if (declaration_ == null) {
              Declaration = new global::Events.Integration.Protobuf.Eli.Rs7Declaration();
            }
            input.ReadMessage(Declaration);
            break;
          }
          case 48: {
            IsAttested = input.ReadBool();
            break;
          }
          case 58: {
            Source = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Rs7AdvanceMonth : pb::IMessage<Rs7AdvanceMonth>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Rs7AdvanceMonth> _parser = new pb::MessageParser<Rs7AdvanceMonth>(() => new Rs7AdvanceMonth());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Rs7AdvanceMonth> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Events.Integration.Protobuf.Eli.Rs7ReceivedReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7AdvanceMonth() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7AdvanceMonth(Rs7AdvanceMonth other) : this() {
      monthNumber_ = other.monthNumber_;
      year_ = other.year_;
      allDay_ = other.allDay_;
      sessional_ = other.sessional_;
      parentLed_ = other.parentLed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7AdvanceMonth Clone() {
      return new Rs7AdvanceMonth(this);
    }

    /// <summary>Field number for the "MonthNumber" field.</summary>
    public const int MonthNumberFieldNumber = 2;
    private int monthNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MonthNumber {
      get { return monthNumber_; }
      set {
        monthNumber_ = value;
      }
    }

    /// <summary>Field number for the "Year" field.</summary>
    public const int YearFieldNumber = 3;
    private int year_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Year {
      get { return year_; }
      set {
        year_ = value;
      }
    }

    /// <summary>Field number for the "AllDay" field.</summary>
    public const int AllDayFieldNumber = 4;
    private int allDay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AllDay {
      get { return allDay_; }
      set {
        allDay_ = value;
      }
    }

    /// <summary>Field number for the "Sessional" field.</summary>
    public const int SessionalFieldNumber = 5;
    private int sessional_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Sessional {
      get { return sessional_; }
      set {
        sessional_ = value;
      }
    }

    /// <summary>Field number for the "ParentLed" field.</summary>
    public const int ParentLedFieldNumber = 6;
    private int parentLed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ParentLed {
      get { return parentLed_; }
      set {
        parentLed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Rs7AdvanceMonth);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Rs7AdvanceMonth other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MonthNumber != other.MonthNumber) return false;
      if (Year != other.Year) return false;
      if (AllDay != other.AllDay) return false;
      if (Sessional != other.Sessional) return false;
      if (ParentLed != other.ParentLed) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MonthNumber != 0) hash ^= MonthNumber.GetHashCode();
      if (Year != 0) hash ^= Year.GetHashCode();
      if (AllDay != 0) hash ^= AllDay.GetHashCode();
      if (Sessional != 0) hash ^= Sessional.GetHashCode();
      if (ParentLed != 0) hash ^= ParentLed.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MonthNumber != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MonthNumber);
      }
      if (Year != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Year);
      }
      if (AllDay != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AllDay);
      }
      if (Sessional != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Sessional);
      }
      if (ParentLed != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ParentLed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MonthNumber != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MonthNumber);
      }
      if (Year != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Year);
      }
      if (AllDay != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AllDay);
      }
      if (Sessional != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Sessional);
      }
      if (ParentLed != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ParentLed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MonthNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MonthNumber);
      }
      if (Year != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Year);
      }
      if (AllDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AllDay);
      }
      if (Sessional != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sessional);
      }
      if (ParentLed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ParentLed);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Rs7AdvanceMonth other) {
      if (other == null) {
        return;
      }
      if (other.MonthNumber != 0) {
        MonthNumber = other.MonthNumber;
      }
      if (other.Year != 0) {
        Year = other.Year;
      }
      if (other.AllDay != 0) {
        AllDay = other.AllDay;
      }
      if (other.Sessional != 0) {
        Sessional = other.Sessional;
      }
      if (other.ParentLed != 0) {
        ParentLed = other.ParentLed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            MonthNumber = input.ReadInt32();
            break;
          }
          case 24: {
            Year = input.ReadInt32();
            break;
          }
          case 32: {
            AllDay = input.ReadInt32();
            break;
          }
          case 40: {
            Sessional = input.ReadInt32();
            break;
          }
          case 48: {
            ParentLed = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            MonthNumber = input.ReadInt32();
            break;
          }
          case 24: {
            Year = input.ReadInt32();
            break;
          }
          case 32: {
            AllDay = input.ReadInt32();
            break;
          }
          case 40: {
            Sessional = input.ReadInt32();
            break;
          }
          case 48: {
            ParentLed = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Rs7EntitlementMonth : pb::IMessage<Rs7EntitlementMonth>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Rs7EntitlementMonth> _parser = new pb::MessageParser<Rs7EntitlementMonth>(() => new Rs7EntitlementMonth());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Rs7EntitlementMonth> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Events.Integration.Protobuf.Eli.Rs7ReceivedReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7EntitlementMonth() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7EntitlementMonth(Rs7EntitlementMonth other) : this() {
      id_ = other.id_;
      monthNumber_ = other.monthNumber_;
      year_ = other.year_;
      days_ = other.days_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7EntitlementMonth Clone() {
      return new Rs7EntitlementMonth(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "MonthNumber" field.</summary>
    public const int MonthNumberFieldNumber = 2;
    private int monthNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MonthNumber {
      get { return monthNumber_; }
      set {
        monthNumber_ = value;
      }
    }

    /// <summary>Field number for the "Year" field.</summary>
    public const int YearFieldNumber = 3;
    private int year_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Year {
      get { return year_; }
      set {
        year_ = value;
      }
    }

    /// <summary>Field number for the "Days" field.</summary>
    public const int DaysFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Events.Integration.Protobuf.Eli.Rs7EntitlementDay> _repeated_days_codec
        = pb::FieldCodec.ForMessage(34, global::Events.Integration.Protobuf.Eli.Rs7EntitlementDay.Parser);
    private readonly pbc::RepeatedField<global::Events.Integration.Protobuf.Eli.Rs7EntitlementDay> days_ = new pbc::RepeatedField<global::Events.Integration.Protobuf.Eli.Rs7EntitlementDay>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Events.Integration.Protobuf.Eli.Rs7EntitlementDay> Days {
      get { return days_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Rs7EntitlementMonth);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Rs7EntitlementMonth other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (MonthNumber != other.MonthNumber) return false;
      if (Year != other.Year) return false;
      if(!days_.Equals(other.days_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (MonthNumber != 0) hash ^= MonthNumber.GetHashCode();
      if (Year != 0) hash ^= Year.GetHashCode();
      hash ^= days_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (MonthNumber != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MonthNumber);
      }
      if (Year != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Year);
      }
      days_.WriteTo(output, _repeated_days_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (MonthNumber != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MonthNumber);
      }
      if (Year != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Year);
      }
      days_.WriteTo(ref output, _repeated_days_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (MonthNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MonthNumber);
      }
      if (Year != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Year);
      }
      size += days_.CalculateSize(_repeated_days_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Rs7EntitlementMonth other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.MonthNumber != 0) {
        MonthNumber = other.MonthNumber;
      }
      if (other.Year != 0) {
        Year = other.Year;
      }
      days_.Add(other.days_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            MonthNumber = input.ReadInt32();
            break;
          }
          case 24: {
            Year = input.ReadInt32();
            break;
          }
          case 34: {
            days_.AddEntriesFrom(input, _repeated_days_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            MonthNumber = input.ReadInt32();
            break;
          }
          case 24: {
            Year = input.ReadInt32();
            break;
          }
          case 34: {
            days_.AddEntriesFrom(ref input, _repeated_days_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Rs7Declaration : pb::IMessage<Rs7Declaration>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Rs7Declaration> _parser = new pb::MessageParser<Rs7Declaration>(() => new Rs7Declaration());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Rs7Declaration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Events.Integration.Protobuf.Eli.Rs7ReceivedReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7Declaration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7Declaration(Rs7Declaration other) : this() {
      fullName_ = other.fullName_;
      contactPhone_ = other.contactPhone_;
      designation_ = other.designation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7Declaration Clone() {
      return new Rs7Declaration(this);
    }

    /// <summary>Field number for the "FullName" field.</summary>
    public const int FullNameFieldNumber = 2;
    private string fullName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FullName {
      get { return fullName_; }
      set {
        fullName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ContactPhone" field.</summary>
    public const int ContactPhoneFieldNumber = 3;
    private string contactPhone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContactPhone {
      get { return contactPhone_; }
      set {
        contactPhone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Designation" field.</summary>
    public const int DesignationFieldNumber = 4;
    private string designation_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Designation {
      get { return designation_; }
      set {
        designation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Rs7Declaration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Rs7Declaration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FullName != other.FullName) return false;
      if (ContactPhone != other.ContactPhone) return false;
      if (Designation != other.Designation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FullName.Length != 0) hash ^= FullName.GetHashCode();
      if (ContactPhone.Length != 0) hash ^= ContactPhone.GetHashCode();
      if (Designation.Length != 0) hash ^= Designation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FullName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FullName);
      }
      if (ContactPhone.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ContactPhone);
      }
      if (Designation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Designation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FullName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FullName);
      }
      if (ContactPhone.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ContactPhone);
      }
      if (Designation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Designation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FullName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullName);
      }
      if (ContactPhone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactPhone);
      }
      if (Designation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Designation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Rs7Declaration other) {
      if (other == null) {
        return;
      }
      if (other.FullName.Length != 0) {
        FullName = other.FullName;
      }
      if (other.ContactPhone.Length != 0) {
        ContactPhone = other.ContactPhone;
      }
      if (other.Designation.Length != 0) {
        Designation = other.Designation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            FullName = input.ReadString();
            break;
          }
          case 26: {
            ContactPhone = input.ReadString();
            break;
          }
          case 34: {
            Designation = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            FullName = input.ReadString();
            break;
          }
          case 26: {
            ContactPhone = input.ReadString();
            break;
          }
          case 34: {
            Designation = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Rs7EntitlementDay : pb::IMessage<Rs7EntitlementDay>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Rs7EntitlementDay> _parser = new pb::MessageParser<Rs7EntitlementDay>(() => new Rs7EntitlementDay());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Rs7EntitlementDay> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Events.Integration.Protobuf.Eli.Rs7ReceivedReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7EntitlementDay() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7EntitlementDay(Rs7EntitlementDay other) : this() {
      dayNumber_ = other.dayNumber_;
      under2_ = other.under2_;
      twoAndOver_ = other.twoAndOver_;
      hours20_ = other.hours20_;
      plus10_ = other.plus10_;
      certificated_ = other.certificated_;
      nonCertificated_ = other.nonCertificated_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Rs7EntitlementDay Clone() {
      return new Rs7EntitlementDay(this);
    }

    /// <summary>Field number for the "DayNumber" field.</summary>
    public const int DayNumberFieldNumber = 1;
    private int dayNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DayNumber {
      get { return dayNumber_; }
      set {
        dayNumber_ = value;
      }
    }

    /// <summary>Field number for the "Under2" field.</summary>
    public const int Under2FieldNumber = 2;
    private int under2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Under2 {
      get { return under2_; }
      set {
        under2_ = value;
      }
    }

    /// <summary>Field number for the "TwoAndOver" field.</summary>
    public const int TwoAndOverFieldNumber = 3;
    private int twoAndOver_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TwoAndOver {
      get { return twoAndOver_; }
      set {
        twoAndOver_ = value;
      }
    }

    /// <summary>Field number for the "Hours20" field.</summary>
    public const int Hours20FieldNumber = 4;
    private int hours20_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hours20 {
      get { return hours20_; }
      set {
        hours20_ = value;
      }
    }

    /// <summary>Field number for the "Plus10" field.</summary>
    public const int Plus10FieldNumber = 5;
    private int plus10_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Plus10 {
      get { return plus10_; }
      set {
        plus10_ = value;
      }
    }

    /// <summary>Field number for the "Certificated" field.</summary>
    public const int CertificatedFieldNumber = 6;
    private int certificated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Certificated {
      get { return certificated_; }
      set {
        certificated_ = value;
      }
    }

    /// <summary>Field number for the "NonCertificated" field.</summary>
    public const int NonCertificatedFieldNumber = 7;
    private int nonCertificated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NonCertificated {
      get { return nonCertificated_; }
      set {
        nonCertificated_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Rs7EntitlementDay);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Rs7EntitlementDay other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DayNumber != other.DayNumber) return false;
      if (Under2 != other.Under2) return false;
      if (TwoAndOver != other.TwoAndOver) return false;
      if (Hours20 != other.Hours20) return false;
      if (Plus10 != other.Plus10) return false;
      if (Certificated != other.Certificated) return false;
      if (NonCertificated != other.NonCertificated) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DayNumber != 0) hash ^= DayNumber.GetHashCode();
      if (Under2 != 0) hash ^= Under2.GetHashCode();
      if (TwoAndOver != 0) hash ^= TwoAndOver.GetHashCode();
      if (Hours20 != 0) hash ^= Hours20.GetHashCode();
      if (Plus10 != 0) hash ^= Plus10.GetHashCode();
      if (Certificated != 0) hash ^= Certificated.GetHashCode();
      if (NonCertificated != 0) hash ^= NonCertificated.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DayNumber != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DayNumber);
      }
      if (Under2 != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Under2);
      }
      if (TwoAndOver != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TwoAndOver);
      }
      if (Hours20 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Hours20);
      }
      if (Plus10 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Plus10);
      }
      if (Certificated != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Certificated);
      }
      if (NonCertificated != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(NonCertificated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DayNumber != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DayNumber);
      }
      if (Under2 != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Under2);
      }
      if (TwoAndOver != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TwoAndOver);
      }
      if (Hours20 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Hours20);
      }
      if (Plus10 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Plus10);
      }
      if (Certificated != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Certificated);
      }
      if (NonCertificated != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(NonCertificated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DayNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DayNumber);
      }
      if (Under2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Under2);
      }
      if (TwoAndOver != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TwoAndOver);
      }
      if (Hours20 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hours20);
      }
      if (Plus10 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Plus10);
      }
      if (Certificated != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Certificated);
      }
      if (NonCertificated != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NonCertificated);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Rs7EntitlementDay other) {
      if (other == null) {
        return;
      }
      if (other.DayNumber != 0) {
        DayNumber = other.DayNumber;
      }
      if (other.Under2 != 0) {
        Under2 = other.Under2;
      }
      if (other.TwoAndOver != 0) {
        TwoAndOver = other.TwoAndOver;
      }
      if (other.Hours20 != 0) {
        Hours20 = other.Hours20;
      }
      if (other.Plus10 != 0) {
        Plus10 = other.Plus10;
      }
      if (other.Certificated != 0) {
        Certificated = other.Certificated;
      }
      if (other.NonCertificated != 0) {
        NonCertificated = other.NonCertificated;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DayNumber = input.ReadInt32();
            break;
          }
          case 16: {
            Under2 = input.ReadInt32();
            break;
          }
          case 24: {
            TwoAndOver = input.ReadInt32();
            break;
          }
          case 32: {
            Hours20 = input.ReadInt32();
            break;
          }
          case 40: {
            Plus10 = input.ReadInt32();
            break;
          }
          case 48: {
            Certificated = input.ReadInt32();
            break;
          }
          case 56: {
            NonCertificated = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DayNumber = input.ReadInt32();
            break;
          }
          case 16: {
            Under2 = input.ReadInt32();
            break;
          }
          case 24: {
            TwoAndOver = input.ReadInt32();
            break;
          }
          case 32: {
            Hours20 = input.ReadInt32();
            break;
          }
          case 40: {
            Plus10 = input.ReadInt32();
            break;
          }
          case 48: {
            Certificated = input.ReadInt32();
            break;
          }
          case 56: {
            NonCertificated = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
